heat_template_version: 2015-04-30

parameters:
    key_name:
      type: string
    image_id:
      type: string
    flavor:
      type: string
    network_name:
      type: string
    subnet_name:
      type: string
    lb_pool_id:
      type: string
    server_name:
      type: string
    ip:
      type: string
    uplink:
      type: string

resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_name }
      fixed_ips:
        - subnet_id: { get_param: subnet_name}
          ip_address: { get_param: ip }
      security_groups:
        - kubernetes_external_sg
        - kubernetes_internal_sg

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: instance_port }
      block_device_mapping_v2:
        - device_name: vda
          delete_on_termination: true
          disk_bus: virtio
          image: { get_param: image_id }
          volume_size: 100

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: uplink }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: instance_port }

  pool_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_param: lb_pool_id }
      address: { get_attr: [ instance, networks, { get_param: network_name }, 0 ] }
      protocol_port: 6443
      subnet: { get_param: subnet_name }

outputs:
  instance_ip:
    description: Internal IP address of the deployed master
    value: { get_attr: [instance, networks, 0, address] }
  floating_ip:
    description: Internal IP address of the deployed master instance
    value: { get_attr: [instance, accessIPv4] }
