heat_template_version: 2015-04-30

parameters:
    key_name:
      type: string
    image_id:
      type: string
    flavor:
      type: string
    network_name:
      type: string
    subnet_name:
      type: string
    server_name:
      type: string
    ip:
      type: string

resources:
  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - fixed_ip: { get_param: ip }
          network: { get_param: network_name }
      security_groups:
        - kubernetes_internal_sg
      block_device_mapping_v2:
        - device_name: vda
          delete_on_termination: true
          disk_bus: virtio
          image: { get_param: image_id }
          volume_size: 100
